<!--
  ~ Time:2022/2/28 17:35 09
  ~ Name:4、promise的异常穿透.html
  ~ Path:Web代码/src/com/charlatan/self_study/promise/基本使用
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<title>异常穿透</title>

</head>
<body>
<pre>
	当使用链式调用的时候，如果有一个出了问题，只需要在链式调用的最后进行catch的处理就能在出错的时候进行解决
</pre>
</body>
<script>
	let pro = new Promise ((resolve, reject) => {
		// resolve('成功')
		reject ('错误')
	})

	pro.then ((value) => {
		console.log (value)
	}).then ((value) => {
		console.log (value)
	}).then ((value) => {
		console.log (value)
	}).catch ((reason) => {
		console.log (reason)
	})
</script>
</html>
