<!--
  ~ Time:2022/3/1 10:01 46
  ~ Name:await.html
  ~ Path:Web代码/src/com/charlatan/self_study/promise/async和wait
  ~ ProjectName:WWW
  ~ Author:charlatan
  ~
  ~  Il n'ya qu'un héroïsme au monde : c'est de voir le monde tel qu'il est et de l'aimer.
  -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta content="IE=edge" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<title>await</title>

</head>
<body>
<pre>
	1. await 右侧的表达式一般为 promise 对象, 但也可以是其它的值
	2. 如果表达式是 promise 对象, await 返回的是 promise 成功的值
	3. 如果表达式是其它值, 直接将此值作为 await 的返回值

	1. await 必须写在 async 函数中, 但 async 函数中可以没有 await
	2. 如果 await 的 promise 失败了, 就会抛出异常, 需要通过 try...catch 捕获处理
</pre>
</body>
<script>
	async function main () {
		let pro = new Promise ((res, rej) => {
			setTimeout (function () {
				// res('ok')
				rej ('err')
			}, 1000)
		})
		try {
			let res = await pro
			console.log (res)
		} catch (e) {
			console.log (e)
		}
	}

	main ()
</script>
</html>
